export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "scope-enum": [
      2,
      "always",
      [
        "extensions",
        "core",
        "chromium",
        "firefox",
        "mcp",
        "examples",
        "root",
        "deps",
        "ci",
        "docs",
        "canon",
        "data",
        "detector",
        "design-md",
        "adapters",
        "plugin",
        "cli",
        "protocol",
        "scripts",
      ],
    ],
  },
};
