import { stringify } from "yaml";
import type { GeneratedTokens } from "./tokens.js";

export interface RenderMeta {
  name: string;
  description: string;
  mode: string;
  stack: string;
  libraries: { components: string; icons: string; fonts: string };
  archetype: { primary: string; secondary?: string; takes?: string[] };
  dials: { variance: number; motion: number; density: number };
  summary: string;
  depth: string;
  layout: string[];
}

function frontmatter(tokens: GeneratedTokens, meta: RenderMeta): string {
  const doc: Record<string, unknown> = {
    name: meta.name,
    description: meta.description,
    colors: tokens.light.colors,
    typography: tokens.typography,
    rounded: tokens.rounded,
    spacing: tokens.spacing,
    elevation: tokens.light.elevation,
    motion: tokens.motion,
    themes: { dark: { colors: tokens.dark.colors, elevation: tokens.dark.elevation } },
    components: {
      "button-primary": {
        backgroundColor: "{colors.primary}",
        textColor: "{colors.on-primary}",
        rounded: "{rounded.md}",
        padding: "{spacing.sm} {spacing.md}",
      },
      "button-secondary": {
        backgroundColor: "{colors.surface}",
        textColor: "{colors.text}",
        rounded: "{rounded.md}",
        padding: "{spacing.sm} {spacing.md}",
      },
      input: {
        backgroundColor: "{colors.surface}",
        textColor: "{colors.text}",
        rounded: "{rounded.sm}",
        padding: "{spacing.sm}",
      },
    },
    northstar: {
      mode: meta.mode,
      stack: meta.stack,
      archetype: meta.archetype,
      libraries: meta.libraries,
      allow: [],
      ignore: [],
    },
  };
  return stringify(doc, { lineWidth: 0 }).trimEnd();
}

function roleList(colors: Record<string, string>): string {
  const notes: Record<string, string> = {
    background: "the page behind everything",
    surface: "cards, panels and inputs",
    text: "primary copy and headings",
    "text-soft": "secondary copy and captions",
    muted: "quiet fills such as table group rows and switch tracks",
    border: "dividers and control outlines",
    primary: "the main action, links and the selected state",
    "on-primary": "text and icons on primary",
    accent: "a single secondary marker, used sparingly",
    danger: "errors and destructive actions",
    success: "confirmations",
    warning: "cautions",
  };
  return Object.entries(colors)
    .map(([role, hex]) => `- ${role}: ${hex}, ${notes[role] ?? "supporting colour"}`)
    .join("\n");
}

export function renderDesign(tokens: GeneratedTokens, meta: RenderMeta): string {
  const secondary = meta.archetype.secondary
    ? ` with ${meta.archetype.secondary} contributing ${(meta.archetype.takes ?? []).join(" and ")}`
    : "";
  const typeRoles = Object.entries(tokens.typography)
    .map(
      ([role, t]) =>
        `- ${role}: ${t.fontFamily} ${t.fontWeight}, ${t.fontSize}${t.letterSpacing ? `, tracking ${t.letterSpacing}` : ""}`,
    )
    .join("\n");
  const radii = Object.entries(tokens.rounded)
    .map(([k, v]) => `${k} ${v}`)
    .join(", ");
  const sections = [
    `# ${meta.name} design system

## Overview

${meta.description} The direction is ${meta.archetype.primary}${secondary}. ${meta.summary} It is a ${meta.mode} design, so the mode sets the motion budget and the density. Taste dials: variance ${meta.dials.variance}, motion ${meta.dials.motion}, density ${meta.dials.density}. Generated by Northstar from a hue and a shape, every colour pair was checked for contrast in both themes.`,
    `## Colors

Neutrals are tinted toward the palette, so no surface is pure black or white. Both themes ship, with the same roles.

${roleList(tokens.light.colors)}

The dark theme lives under themes.dark and keeps every role. Text on surface passes 7:1 and every other pair passes 4.5:1 in both themes.`,
    `## Typography

${typeRoles}

Tracking tightens as size grows and opens slightly below 13px. Headings use balanced wrapping, body paragraphs use pretty wrapping. Prices, totals and table figures use tabular numerals.`,
    `## Layout

Base unit 4px. Spacing steps: ${Object.entries(tokens.spacing)
      .filter(([k]) => k !== "unit")
      .map(([k, v]) => `${k} ${v}`)
      .join(
        ", ",
      )}. ${meta.layout.join(". ")}. Use dynamic viewport units for full height sections. Below 640px everything collapses to one column and nothing scrolls horizontally outside its own container.`,
    `## Elevation & Depth

${meta.depth} Shadows come from the elevation tokens: each level is a one pixel ring plus two soft layers tinted toward the surface hue, never a single black layer. Dark theme rings turn light and shadows deepen. Reach for xs on controls, sm and md on cards, lg on menus and xl on dialogs.`,
    `## Shapes

Radius scale: ${radii}. Each step adds the padding of the container it sits in, so a child radius equals its parent radius minus the padding between them. Icons come from ${meta.libraries.icons} at one size and one stroke, with the stroke raised by 0.5 beside semibold text. Images get a one pixel outline at ten percent opacity.`,
    `## Components

Components come from ${meta.libraries.components} and are restyled with these tokens. Every control supports default, hover, focus visible, active, disabled and loading, plus empty and error where data is involved. Hover effects only apply when a device can hover. Pressed controls scale to 0.97 over ${tokens.motion["duration-fast"]}. Motion uses ${tokens.motion["ease-out"]} for entrances and feedback, durations ${tokens.motion["duration-fast"]} to ${tokens.motion["duration-slow"]} for controls and ${tokens.motion["duration-drawer"]} for drawers.`,
    `## Do's and Don'ts

| Do | Don't |
|---|---|
| Use tokens by reference | Write raw colour, shadow or spacing values in code |
| Take components, icons and fonts from the chosen libraries | Hand roll overlays, icons or font loading |
| Keep one bold choice per screen | Add competing accents |
| Provide a reduced motion path | Animate layout properties or use ease in |
| Keep borders on the neutral ramp | Use pale saturated borders |`,
  ];
  return `---\n${frontmatter(tokens, meta)}\n---\n\n${sections.join("\n\n")}\n`;
}
