export type {
  Comment,
  CommentMetadata,
  CommentStatus,
  ComponentFrame,
  ComponentInfo,
  DeferralNotice,
  DeferredComment,
  Draft,
  ElementInfo,
  Intent,
  LocateConfidence,
  LocateEntry,
  LocateKind,
  Operation,
  OperationType,
  PageInfo,
  Resolution,
  RouteInfo,
  SourceLocation,
  Target,
  TargetAncestor,
} from "@northstar/protocol";
